
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env

  redpanda:
    image: redpandadata/redpanda:v23.3.3
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: curl --fail http://localhost:9644/v1/status/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"  # OTLP HTTP
      - "4317:4317"  # OTLP gRPC

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      POSTGRES_DSN: ${POSTGRES_DSN}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      SERVICE_NAME: order-service
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      otel-collector:
        condition: service_started
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"  # Localhost access: http://localhost:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: ${POSTGRES_EXPORTER_DSN}
    depends_on:
      - postgres

  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4320:4320"    # OTLP gRPC
    restart: unless-stopped

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    ports:
      - "9308:9308"
    command:
      - --kafka.server=redpanda:9092
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  pg_data:
  grafana-storage:
