# prometheus.yml
global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8000']
  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
